plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

group 'by.pilipuk'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter:3.5.0")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.5.0")
    implementation("org.springframework.boot:spring-boot-starter-web:3.5.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.5.0")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation("org.projectlombok:lombok:1.18.38")
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    implementation("org.postgresql:postgresql:42.7.7")
}

test {
    useJUnitPlatform()
}